version: '3'

services:

  billingdb: 
    image: mysql:8.0.26
    networks:
      - coolnet
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234!
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost:3306"]
            timeout: 20s
            retries: 10
     

  billingapp:
    build: .
    networks:
      - coolnet    
    volumes:
      - ./rates:/in
    ports:
      - 8081:8081
    depends_on:
      - "billingdb"

volumes:
  mysqldata:
    
networks:
  coolnet:
    driver: bridge

