version: '3.3'

services:

  billingdb: 
    image: mysql:8.0.26
    networks:
      - prod_default
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234!
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost:3306"]
            timeout: 20s
            retries: 10
     
           

  billingapp:
    networks:
      - prod_default
    build: .
    volumes:
      - ./rates:/in
    ports:
      - 8081:8081
    depends_on:
      - "billingdb"



networks:
  prod_default:
    driver: bridge
